[mypy]
python_version = 3.14
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true

[mypy-jax.*]
ignore_missing_imports = true

[mypy-jaxlib.*]
ignore_missing_imports = true
